#!/bin/env bash

## General

prog="${0##*/}"
ver=1.0
window_icon="/usr/share/icons/hicolor/96x96/apps/sos-Easy-Install.png"
image_icon="/usr/share/pixmaps/sosEI-header.png"
license="/usr/share/licenses/sos-easy-install/COPYING"
arch=$(uname -m)

## Functions


# Checking user's privileges
if [[ $EUID -ne 0 ]]; then
  yad --text="Програмата трябва да се стартира с правата на потребител root.\nСтартирайте отново, по следният начин:\n\n<b>su -c '$prog'</b>\nили\n<b>beesu $prog</b>" \
      --window-icon="$window_icon" \
      --title="$prog" \
      --width="450" --height="200" \
      --button="ОК":0 --button="Затваряне":1 \
      --center
  exit 1
fi

# KILL previous YUM
pkill -SIGKILL -u root -o yum


# Checking installed packages
isInstalled(){
  rpm -q --quiet "$1"
}

# Notify message
notifyUser(){
  yad --title="$prog" --window-icon="$window_icon" --image=gtk-dialog-info --button="Затваряне":1 --text="$1" --center
}

install_steam() {
  if isInstalled steam; then
    notifyUser "Пакета Steam е вече инсталиран"
  elif [ ! -f /etc/yum.repos.d/scx-el6-steam.repo ]; then
    pushd /etc/yum.repos.d/
    wget --no-check-certificate --quiet "https://soyuz.asia/repos/el/6/scx-el6-steam/scx-el6-steam.repo"
    popd
  elif [[ "$arch" == "x86_64" ]]; then
    cat << EOF > /etc/yum.repos.d/adobe-linux-i386.repo
[adobe-linux-i386]
name=Adobe Systems Incorporated
baseurl=http://linuxdownload.adobe.com/linux/i386/
enabled=1
skip_if_unavailable=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
EOF
   # disable yum to verify SSL certificates (This is a temporary workaround!)
   # FIX: Peer cert cannot be verified or peer cert invalid
   sed -i '/^\[main\]$/a sslverify=False' /etc/yum.conf
   yum --enablerepo="scx-el6-steam" --nogpgcheck install -y flash-plugin.i386 flash-plugin.x86_64 SDL_image.i686 SDL_image.x86_64 steam steam-deps 2>&1 | yad --title='Инсталиране на Steam' \
         --text='Моля изчакайте....' \
         --height=250 --width=500 \
         --progress --pulsate --auto-close --auto-kill \
         --window-icon="$window_icon" \
         --button "Затваряне":1 \
         --image=system-software-install \
         --center
   sed -i -e 's|Exec=steam|Exec=/usr/local/bin/steam|g' /usr/share/applications/steam.desktop
   setsebool -P allow_execheap 1
   notifyUser "Инсталирането на Steam приключи"
  else
    # disable yum to verify SSL certificates (This is a temporary workaround!)
    # FIX: Peer cert cannot be verified or peer cert invalid
    sed -i '/^\[main\]$/a sslverify=False' /etc/yum.conf
    yum --enablerepo="scx-el6-steam" --nogpgcheck install -y steam steam-deps 2>&1 | yad --title='Инсталиране на Steam' \
         --text='Моля изчакайте....' \
         --height=250 --width=500 \
         --progress --pulsate --auto-close --auto-kill \
         --window-icon="$window_icon" \
         --button "Затваряне":1 \
         --image=system-software-install \
         --center
    sed -i -e 's|Exec=steam|Exec=/usr/local/bin/steam|g' /usr/share/applications/steam.desktop
    setsebool -P allow_execheap 1
    notifyUser "Инсталирането на Steam приключи"
  fi
  # Revert yum to verify SSL certificates
  sed -i '/sslverify/d' /etc/yum.conf
}

install_dropbox() {
  if isInstalled nautilus-dropbox; then
    notifyUser "Пакета Dropbox е вече инсталиран"
  else
    if [[ "$arch" == "x86_64" ]]; then
      yum localinstall --nogpgcheck -y "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-1.6.2-1.fedora.x86_64.rpm" 2>&1 | yad --title='Инсталиране на Dropbox' \
          --text='Моля изчакайте....' \
          --height=250 --width=500 \
          --progress --pulsate --auto-close --auto-kill \
          --window-icon="$window_icon" \
          --button "Затваряне":1 \
          --image=system-software-install \
          --center
      rm -f /etc/yum.repos.d/dropbox.repo
      notifyUser "Инсталирането на Dropbox приключи"
    else
      yum localinstall --nogpgcheck -y "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-1.6.2-1.fedora.i386.rpm" 2>&1 | yad --title='Инсталиране на Dropbox' \
          --text='Моля изчакайте....' \
          --height=250 --width=500 \
          --progress --pulsate --auto-close --auto-kill \
          --window-icon="$window_icon" \
          --button "Затваряне":1 \
          --image=system-software-install
          --center
      rm -f /etc/yum.repos.d/dropbox.repo
      notifyUser "Инсталирането на Dropbox приключи"
    fi
  fi
}

install_chrome() {
  if isInstalled google-chrome-stable; then
    notifyUser "Пакета Google Chrome е вече инсталиран"
  else
    if [[ "$arch" == "x86_64" ]]; then
      yum --nogpgcheck install -y chrome-deps "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" 2>&1 | yad --title='Инсталиране на Google Chrome' \
          --text='Моля изчакайте....' \
          --height=250 --width=500 \
          --progress --pulsate --auto-close --auto-kill \
          --window-icon="$window_icon" \
          --button "Затваряне":1 \
          --image=system-software-install \
          --center
      notifyUser "Исталирането на Google Chrome приключи"
   else
      yum --nogpgcheck install -y chrome-deps "https://dl.google.com/linux/direct/google-chrome-stable_current_i386.rpm" 2>&1 | yad --title='Инсталиране на Google Chrome' \
          --text='Моля изчакайте....' \
          --height=250 --width=500 \
          --progress --pulsate --auto-close --auto-kill \
          --window-icon="$window_icon" \
          --button "Затваряне":1 \
          --image=system-software-install \
          --center
      notifyUser "Исталирането на Google Chrome приключи"
    fi
  fi
}

install_chromium() {
  if isInstalled chromium-browser; then
    notifyUser "Пакета Chromium е вече инсталиран"
  else
    yum --nogpgcheck install -y chromium-browser 2>&1 | yad --title='Инсталиране на Chromium' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
  notifyUser "Инсталирането на Chromium приключи"
  fi
}

install_skype() {
  if isInstalled skype; then
    notifyUser "Пакета Skype е вече инсталиран"
  else
    yum --nogpgcheck install -y skype 2>&1 | yad --title='Инсталиране на Skype' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
  notifyUser "Инсталирането на Skype приключи"
  fi
}

install_virtualbox() {
  if isInstalled VirtualBox-4.3; then
    notifyUser "Пакета VirtualBox-4.3 е вече инсталиран"
  else
    yum --nogpgcheck install -y gcc make patch dkms qt libgomp kernel-headers kernel-devel fontforge binutils glibc-headers glibc-devel VirtualBox-4.3 2>&1 | yad --title='Инсталиране на VirtualBox-4.3' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
       --image=system-software-install \
       --center
    service vboxdrv setup
    notifyUser "Инсталирането на VirtualBox-4.3 приключи"
  fi
}

install_teamviewer() {
  if isInstalled teamviewer; then
    notifyUser "Пакета TeamViewer е вече инсталиран"
  else
    yum localinstall --nogpgcheck -y "http://www.teamviewer.com/download/teamviewer_linux.rpm" 2>&1 | yad --title='Инсталиране на TeamViewer' \
         --text='Моля изчакайте....' \
         --height=250 --width=500 \
         --progress --pulsate --auto-close --auto-kill \
         --window-icon="$window_icon" \
         --button "Затваряне":1 \
         --image=system-software-install \
         --center
  notifyUser "Инсталирането на TeamViewer приключи"
  fi
}

install_mscorefonts(){
  if isInstalled msttcorefonts; then
    notifyUser "Пакета Msttcorefonts е вече инсталиран"
  else
    yum --nogpgcheck install msttcorefonts -y 2>&1 | yad --title='Инсталиране на Msttcorefonts' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
    notifyUser "Инсталирането на Msttcorefonts приключи"
  fi
}

infinalityShowstyles(){
 showStyles=$(yad --list \
            --title="$prog" \
            --text "Изберете стил по подразбиране за шрифтовете" \
            --width="300" --height="400" \
            --button="ОК":0 --button="Затваряне":1 \
            --window-icon="$window_icon" \
            --center \
            --column 'Стил' \
            "1) debug" \
            "2) infinality" \
            "3) linux" \
            "4) osx" \
            "5) osx2" \
            "6) win7" \
            "7) win98" \
            "8) winxp" )
  ret=$?

  if [[ "$ret" -eq "1" ]]; then
     yad --text="Грешка: Не сте избрали стил." \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
  fi

  case ${showStyles} in
    "1) debug"*) sh /etc/fonts/infinality/infctl.sh setstyle debug >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=DEBUG/g' /etc/profile.d/infinality-settings.sh ;;
    "2) infinality"*) sh /etc/fonts/infinality/infctl.sh setstyle infinality >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=INFINALITY/g' /etc/profile.d/infinality-settings.sh ;;
    "3) linux"*) sh /etc/fonts/infinality/infctl.sh setstyle linux >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=LINUX/g' /etc/profile.d/infinality-settings.sh ;;
    "4) osx"*) sh /etc/fonts/infinality/infctl.sh setstyle osx >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=OSX/g' /etc/profile.d/infinality-settings.sh ;;
    "5) osx2"*) sh /etc/fonts/infinality/infctl.sh setstyle osx2 >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=OSX/g' /etc/profile.d/infinality-settings.sh;;
    "6) win7"*) sh /etc/fonts/infinality/infctl.sh setstyle win7 >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=WINDOWS/g' /etc/profile.d/infinality-settings.sh ;;
    "7) win98"*) sh /etc/fonts/infinality/infctl.sh setstyle win98 >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=WINDOWS/g' /etc/profile.d/infinality-settings.sh  ;;
    "8) winxp"*) sh /etc/fonts/infinality/infctl.sh setstyle winxp >/dev/null && sed -i 's/^USE_STYLE=.*$/USE_STYLE=WINDOWS/g' /etc/profile.d/infinality-settings.sh ;;
    #*) exit ;;

  esac

}

install_infinality(){
  if isInstalled freetype-infinality; then
    notifyUser "Пакета infinality е вече инсталиран - затворете този диалог за да смените стила на шрифтовете"
    infinalityShowstyles
  else
    yum --nogpgcheck install freetype-infinality fontconfig-infinality msttcorefonts -y 2>&1 | yad --title='Инсталиране и настройка на Infinality' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center

    infinalityShowstyles
    notifyUser "Инсталирането на Infinality приключи"
  fi
}

addSudo() {
  user=$(yad --entry \
             --title="Име на потребител" \
             --width=250 --height=200 \
             --text="Моля, въведете потребителско име:" \
             --button="ОК":0 --button="Затваряне":1 \
             --center)
  if [[ -z $user ]] ; then
    yad --text="Грешка: Не сте въвели потребителско име!" \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-warning \
        --center
  elif grep --quiet -w "$user ALL=(ALL) ALL" /etc/sudoers; then
    yad --text="Грешка: Вече са били добавени sudo права за потребителя $user!" \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-warning \
        --center
  else
    echo "$user ALL=(ALL) ALL" >> /etc/sudoers
    notifyUser "Добавени са sudo права за потребителя '$user'"
  fi
}

setSelinux() {
  if grep --quiet ^SELINUX=permissive$ /etc/selinux/config; then
    setenforce 1 > /dev/null
    sed -i 's/^SELINUX=.*$/SELINUX=enforcing/g' /etc/selinux/config
    notifyUser "Включване на SELinux!"
  else
    setenforce 0 > /dev/null
    sed -i 's/^SELINUX=.*$/SELINUX=permissive/g' /etc/selinux/config
    notifyUser "Изключване на SELinux!"
  fi
}

install_compiz(){
  if ! isInstalled glx-utils; then
    yum --nogpgcheck install -y glx-utils 2>&1 | yad --title='Инсталиране на Glx-utils' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
  elif isInstalled compiz-fusion ccsm; then
    notifyUser "Пакета Compiz-fusion е вече инсталиран"
  elif [[ $( glxinfo | grep direct) == *"direct rendering: Yes"* ]]; then
    yum --nogpgcheck install -y ccsm emerald-themes compizconfig-backend-gconf fusion-icon-gtk emerald compiz-fusion compiz-fusion-gnome libcompizconfig compiz-gnome compiz-bcop compiz compizconfig-python compiz-fusion-extras compiz-fusion-extras-gnome 2>&1 | yad --title='Инсталиране на CompizFusion' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
    notifyUser "Инсталирането на Compiz-Fusion приключи"
  else
    yad --text="Грешка: Явно не използвате видео драйвер с поддръжка на 3D-ускорение." \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
  fi
}

install_playonlinux(){
  if isInstalled playonlinux; then
    notifyUser "Пакета PlayOnLinux е вече инсталиран"
  elif [[ ! -f /etc/yum.repos.d/playonlinux.repo ]]; then
    yum-config-manager --add-repo http://rpm.playonlinux.com/playonlinux.repo 2>&1
    yum --nogpgcheck install -y nc playonlinux 2>&1 | yad --title='Инсталиране на PlayOnLinux' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
    notifyUser "Инсталирането на PlayOnLinux приключи"
  else
    yum --nogpgcheck install -y nc playonlinux 2>&1 | yad --title='Инсталиране на PlayOnLinux' \
        --text='Моля изчакайте....' \
        --height=250 --width=500 \
        --progress --pulsate --auto-close --auto-kill \
        --window-icon="$window_icon" \
        --button "Затваряне":1 \
        --image=system-software-install \
        --center
    notifyUser "Инсталирането на PlayOnLinux приключи"
  fi
}

# Show about dialog
info() {
  yad --title="$prog" --text-align=left --text="<span font_weight='bold' font='17'>$prog $ver </span>\n\n\Програма, която ви позволява да инсталирате допълнителен софтуер като Skype, Chrome, Steam и др., също така, дава възможност да настройте допълнително вашата StotinkaOS, само с няколко щраквания на мишката.   \n\n<span font='9'>Copyright © 2015 StotinkaOS Team\nwebsite: <a href='http://stotinkaos.net'>http://stotinkaos.net</a></span>" \
      --window-icon="$window_icon" \
      --width="200" --height="300" \
      --button="ОК":0 --button="Лиценз":2 --button="Затваряне":1 \
      --image="$window_icon" \
      --center
  ret=$?

  if [[ "$ret" -eq "2" ]]; then
    yad --title="$prog" --text-info --filename="$license" \
        --window-icon="$window_icon" \
        --width="500" --height="300" \
        --button="Затваряне":1 \
        --center
  fi
  menu
}

# Main menu
menu(){
while :
do
  choise=$(yad --title="$prog" --class="$prog" --name="$prog" \
               --image="$image_icon" --image-on-top --window-icon="$window_icon" \
               --width="450" --height="500" --center \
               --print-column=2 --list --radiolist --column "Избери" --column dummy --column "Действие" --hide-column 2 \
               --button="ОК":0 --button="gtk-about":2 --button="Затваряне":1 \
               false 0 "Инсталиране на Steam" \
               false 1 "Инсталиране на Dropbox" \
               false 2 "Добавяне на sudo команда за потребител" \
               false 3 "Инсталиране на Google Chrome" \
               false 4 "Инсталиране на Chromium" \
               false 5 "Инсталиране на Skype" \
               false 6 "Инсталиране на TeamViewer" \
               false 7 "Инсталиране на Msttcorefonts (Microsoft шрифтове)" \
               false 8 "Оптимизиране на шрифтовете със Infinality" \
               false 9 "Инсталиране на VirtualBox-4.3" \
               false 10 "Инсталиране на Compiz-Fusion" \
               false 11 "Инсталиране на PlayOnLinux" \
               false 12 "Изключване - Включване на SELinux");
  ret=$?

  if [[ "$ret" -eq "2" ]]; then
    info
  fi

  case ${choise} in
    "0|")install_steam ;;
    "1|")install_dropbox ;;
    "2|")addSudo ;;
    "3|")install_chrome ;;
    "4|")install_chromium ;;
    "5|")install_skype ;;
    "6|")install_teamviewer ;;
    "7|")install_mscorefonts ;;
    "8|")install_infinality ;;
    "9|")install_virtualbox ;;
    "10|")install_compiz ;;
    "11|")install_playonlinux ;;
    "12|")setSelinux ;;
    *) break ;;
  esac
done
}

menu

# Please report bugs at <http://www.stotinkaos.net/forums>
# End of the Script
