#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global

switching_gnome(){
  yad --width="520" --height="300" \
      --window-icon="$window_icon" \
      --image="$gnomeIcon" \
      --title="$prog - Опция Gnome сесия" \
      --text="<b>GNOME Сесия</b>
Потребителите може да превключват от класически GNOME на GNOME Shell сесия и обратното ." \
      --button="GNOME SHELL":1 --button="GNOME CLASSIC":2 \
      --center
  ret=$?

  if [[ "$ret" -eq "1" ]]; then
    runuser -l ${user} -c 'gnome-shell --mode=user -r &'
    log "INFO:Преминавана в GNOME SHELL сесия"
  elif [[ "$ret" -eq "2" ]]; then
    runuser -l ${user} -c 'gnome-shell --mode=classic -r &'
    log "INFO:Преминавана в GNOME CLASSIC сесия"
  fi
}

switching_gnome
