#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global

install_steam() {
  if isInstalled steam; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Steam" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$steam_Image" --borders=20 \
      --text="<b>Steam</b>
Софтуерна, мултиплейър и комуникационна платформа за разпространение на цифрово съдържание и мултимедия, разработена от Valve Corporation.
Steam има също и обществени функции, автоматични обновления на игрите, и възможност за гласов и текстов чат в игра.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Games
<b><span color='dark gray'>Хранилище</span></b>  negativo17 - steam
<b><span color='dark gray'>Лиценз</span></b>  <a href='http://store.steampowered.com/eula/eula_39190'>EULA</a>
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://store.steampowered.com/'>http://store.steampowered.com/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage steam flash-plugin.i386
      # remove steam repo
      rm -f /etc/yum.repos.d/epel-steam.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      # add steam repo
      yum-config-manager --add-repo=http://negativo17.org/repos/epel-steam.repo
      # import GPG key
      rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-i386-1.0-1.noarch.rpm
      rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
      rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
      # install steam
      installPackage flash-plugin.i386 flash-plugin.x86_64 steam libtxc_dxtn.x86_64
      # remove incompatible repo (This is a temporary workaround!)
      rm -f /etc/yum.repos.d/epel-handbrake.repo
      # allow Steam to start in Big Picture mode
      setsebool -P allow_execheap 1
    fi
  fi
}

install_dropbox() {
  if isInstalled nautilus-dropbox; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Dropbox" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$dropbox_Image" --borders=20 \
      --text="<b>Dropbox</b>
Разширение за файловият мениджър Nautilus, което интегрира облак услугата Dropbox със GNOME десктопа.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → File Transfer
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-3.0'>GPLv3</a>
<b><span color='dark gray'>Обем</span></b>  205,3 kB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.dropbox.com'>https://www.dropbox.com</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage nautilus-dropbox
    elif [[ "$BtStatus" == Инсталирай ]]; then
      # find latest version
      URL=$(wget "https://www.dropbox.com/install?os=lnx" -O - | tr ' ' '\n' | grep -o "nautilus-dropbox-[0-9]*.[0-9]*.[0-9]*-[0-9]*.fedora.x86_64.rpm" | head -n 1 | sed -e 's/^/http:\/\/linux.dropbox.com\/packages\/fedora\//')
      installPackage "$URL"
      rm -f /etc/yum.repos.d/dropbox.repo
    fi
  fi
}

install_viber(){
  if isInstalled viber; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Viber" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$viber_Image" --borders=20 \
      --text="<b>Viber</b>
Безплатни разговори, обмен на съобщения и файлове с всеки, и навсякъде.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Instant Messaging
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://www.viber.com/en/eula'>EULA</a>
<b><span color='dark gray'>Обем</span></b>  352,2 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://www.viber.com/en/'>http://www.viber.com/en/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage viber
      rm -f usr/bin/Viber
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage qt5-qtbase-gui https://download.cdn.viber.com/desktop/Linux/viber.rpm
      # fix $PATH
      ln -s /opt/viber/Viber /usr/bin/Viber
    fi
  fi
}

install_rambox(){
  if isInstalled Rambox; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Rambox" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$rambox_Image" --borders=20 \
      --text="<b>Rambox</b>
Безплатна, с отворен код платформа за съобщения и имейл приложение, което съчетава в себе си общите уеб-приложения в едно.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Instant Messaging
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-3.0'>GPLv3</a>
<b><span color='dark gray'>Обем</span></b>  126 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://rambox.pro/'>http://rambox.pro/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage Rambox
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage https://github.com/saenzramiro/rambox/releases/download/0.5.3/Rambox-0.5.3-x64.rpm
    fi
  fi
}

install_telegram(){
  if isInstalled telegram-desktop; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Telegram" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$telegram_Image" --borders=20 \
      --text="<b>Telegram</b>
Приложение за съобщения с акцент върху скоростта и сигурността, telegram е супер бърз, лесен и безплатен .

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Instant Messaging
<b><span color='dark gray'>Хранилище</span></b>  rommon-telegram
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-3.0'>GPLv3</a>
<b><span color='dark gray'>Обем</span></b>  70,1 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://telegram.org/'>https://telegram.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage telegram-desktop
      rm -f /etc/yum.repos.d/rommon-telegram-epel-7.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat << EOF > /etc/yum.repos.d/rommon-telegram-epel-7.repo
[rommon-telegram]
name=Copr repo for telegram owned by rommon
baseurl=https://copr-be.cloud.fedoraproject.org/results/rommon/telegram/epel-7-x86_64/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/rommon/telegram/pubkey.gpg
enabled=1
enabled_metadata=1
EOF
      installPackage telegram-desktop
    fi
  fi
}

install_spotify(){
  if isInstalled spotify-client; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Spotify Client" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$spotify_Image" --borders=20 \
      --text="<b>Spotify Client</b>
Музикална услуга, предлагаща легален стрийминг на музика от много лейбъли, включително Sony, EMI, Warner и Universal.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Audio → Music
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://www.spotify.com/legal/end-user-agreement'>EULA</a>
<b><span color='dark gray'>Обем</span></b>  167,9 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.spotify.com/bg/'>www.spotify.com/bg/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage spotify-client
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage spotify-client
    fi
  fi
}

install_sublimetext(){
  if isInstalled sublime_text; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Sublime Text 3" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$sublimetext_Image" --borders=20 \
      --text="<b>Sublime Text 3</b>
Междуплатформен софтуер за обработка на изходен код и текстов редактор с приложно-програмен интерфейс (API) написан на Python.
Функционалността му може да бъде допълвана от потребителите чрез плъгини.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Utilities → Text Editor
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://www.sublimetext.com/eula'>EULA</a>
<b><span color='dark gray'>Обем</span></b>  21 MB
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.sublimetext.com/3'>www.sublimetext.com/3</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage sublime_text
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage sublime_text
    fi
  fi
}

install_atom() {
  if isInstalled atom; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Atom Text Editor" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$atom_Image" --borders=20 \
      --text="<b>Atom Text Editor</b>
Свободен и отворен код текстов редактор за OS X, Linux и Windows с поддръжка на плъгини разработен от github.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория </span></b>  Utilities → Text Editor
<b><span color='dark gray'>Хранилище</span></b>  mosquito-atom-epel-7
<b><span color='dark gray'>Лиценз </span></b>  <a href='https://spdx.org/licenses/MIT.html'>MIT</a>
<b><span color='dark gray'>Обем </span></b>  75 MB
<b><span color='dark gray'>Уеб сайт </span></b>  <a href='https://atom.io/'>https://atom.io/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage atom
      rm -f /etc/yum.repos.d/mosquito-atom-epel-7.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      yum-config-manager --add-repo="https://copr.fedorainfracloud.org/coprs/mosquito/atom/repo/epel-7/mosquito-atom-epel-7.repo"
      installPackage atom
    fi
  fi
}

install_gtalk() {
  if isInstalled google-talkplugin; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★☆☆☆☆</span>'
  yad --title="Google Talk Plugin" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$gtalk_Image" --borders=20 \
      --text="<b>Google Talk Plugin</b>
Провеждайте гласови и видеоразговори от компютъра си.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Instant Messaging
<b><span color='dark gray'>Хранилище</span></b>  google-talkplugin
<b><span color='dark gray'>Лиценз</span></b>  Безплатна програма, Google условия за ползване на услугата.
<b><span color='dark gray'>Обем</span></b>  17 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='www.google.com/chat/video'>www.google.com/chat/video</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage google-talkplugin
      rm -f /etc/yum.repos.d/google-talkplugin.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
cat << EOF > /etc/yum.repos.d/google-talkplugin.repo
[google-talkplugin]
name=google-talkplugin
baseurl=http://dl.google.com/linux/talkplugin/rpm/stable/x86_64
enabled=1
gpgcheck=1
skip_if_unavailable=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-google-talkplugin
EOF
      installPackage google-talkplugin
    fi
  fi
}

install_chrome() {
  if isInstalled google-chrome-stable; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Google Chrome" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$chrome_Image" --borders=20 \
      --text="<b>Google Chrome</b>
Безплатен уеб браузър на компанията Google.

$stars

<b>Детайли:</b>
<b><span color='dark gray'>Категория:</span></b>  Internet → Web Browser
<b><span color='dark gray'>Хранилище</span></b>  google-chrome
<b><span color='dark gray'>Лиценз:</span></b>  <a href='https://www.google.com/chrome/browser/privacy/eula_text.html'>EULA</a>
<b><span color='dark gray'>Обем:</span></b>  179,0 MB
<b><span color='dark gray'>Уеб сайт:</span></b>  <a href='https://www.google.com/chrome/'>https://www.google.com/chrome</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage google-chrome-stable
      rm -f /etc/yum.repos.d/google-chrome.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat > /etc/yum.repos.d/google-chrome.repo << EOF_GOOGLE_CHROME_REPO
[google-chrome]
name=google-chrome
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
skip_if_unavailable=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF_GOOGLE_CHROME_REPO
      installPackage google-chrome-stable
    fi
  fi
}

install_ownCloud_client(){
  if isInstalled owncloud-client; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="The ownCloud Client" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$ownCloud_Image" --borders=20 \
      --text="<b>The ownCloud Client</b>
Позволява да се свържете към вашия собствен ownCloud сървър.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → File Transfer
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Обем</span></b>  5,2 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://owncloud.org/'>https://owncloud.org</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage owncloud-client
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage owncloud-client
    fi
  fi
}

install_skype() {
  if isInstalled skypeforlinux; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">☆☆☆☆☆</span>'
  yad --title="Skype for Linux Alpha" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$skype_Image" --borders=20 \
      --text="<b>Skype for Linux Alpha</b>
Приложен софтуер за чат, VOIP телефония и видеовръзка.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Instant Messaging
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://www.skype.com/en/legal/ios/tos/#4'>EULA</a>
<b><span color='dark gray'>Обем</span></b>  155,3 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.skype.com/'>https://www.skype.com</a>" \
      --button="$BtStatus":0 \
      --center
 ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage skypeforlinux
    elif [[ "$BtStatus" == Инсталирай ]]; then
      # remove old skype repo
      rm -f /etc/yum.repos.d/skype.repo
      installPackage "https://go.skype.com/skypeforlinux-64-alpha.rpm"
    fi
  fi
}

install_teamviewer() {
  if isInstalled teamviewer; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="TeamViewer" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$teamv_Image" --borders=20 \
      --text="<b>TeamViewer</b>
Установете входящи и изходящи отдалечени връзки за поддръжка в реално време или достъп до други компютри.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet
<b><span color='dark gray'>Лиценз</span></b>  Патентован, безплатен за некомерсиална употреба.
<b><span color='dark gray'>Обем</span></b>  150,5 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://teamviewer.com/'>http://teamviewer.com</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage teamviewer
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage "http://download.teamviewer.com/download/teamviewer.i686.rpm"
    fi
  fi
}

install_tor() {
  if isInstalled torbrowser-launcher; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Tor Browser Launcher" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$tor_Image" --borders=20 \
      --text="<b>Tor Browser Launcher</b>
Надеждно и лесно изтегляне, проверяване, инсталиране и стартиране на Tor браузъра в Linux .

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Web Browser
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/MIT.html'>MIT</a>
<b><span color='dark gray'>Обем</span></b>  297 K
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://github.com/micahflee/torbrowser-launcher'>https://github.com/micahflee/torbrowser-launcher</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage torbrowser-launcher
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage torbrowser-launcher
    fi
  fi
}

install_mscorefonts(){
  if isInstalled msttcore-fonts-installer; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="msttcore-fonts-installer" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$ms_Image" --borders=20 \
      --text="<b>Msttcorefonts installer</b>
Инсталатор на Microsoft TrueType шрифтове за по добра Windows съвместимост на определени приложения.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b> Fonts
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b> <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Обем</span></b> 24 K
<b><span color='dark gray'>Уеб сайт</span></b> <a href='http://mscorefonts2.sourceforge.net/'>http://mscorefonts2.sourceforge.net</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage msttcore-fonts-installer
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage msttcore-fonts-installer
    fi
  fi
}

install_playonlinux(){
  if isInstalled playonlinux; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★☆☆☆☆</span>'
  yad --title="PlayOnLinux" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$playonlinux_Image" --borders=20 \
      --text="<b>PlayOnLinux</b>
Стартирайте лесно видео игри, Microsoft Office и др. любими приложения в Linux.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Games
<b><span color='dark gray'>Хранилище</span></b>  playonlinux
<b><span color='dark gray'>Лиценз</span></b>   <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.playonlinux.com/en/'>https://www.playonlinux.com/en</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage playonlinux
      rm -f /etc/yum.repos.d/playonlinux.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat > /etc/yum.repos.d/playonlinux.repo << EOF_PLAYONLINUX_REPO
[playonlinux]
name=PlayOnLinux Official repository
baseurl=http://rpm.playonlinux.com/fedora/yum/base
enable=1
gpgcheck=0
skip_if_unavailable=1
gpgkey=http://rpm.playonlinux.com/public.gpg
EOF_PLAYONLINUX_REPO
      installPackage nc mesa-libGL.i686 mesa-libGLU.i686 mesa-dri-drivers.i686 SDL.i686 libGLEW.i686 playonlinux
    fi
  fi
}

install_megasync(){
  if isInstalled megasync nautilus-megasync; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="MEGASync client" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$mega_Image" --borders=20 \
      --text="<b>MEGASync client</b>
Разширение за файловият мениджър Nautilus, което интегрира облак услугата MEGA със GNOME десктопа.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → File Transfer
<b><span color='dark gray'>Хранилище</span></b>  MEGAsync
<b><span color='dark gray'>Лиценз</span></b>  Freeware
<b><span color='dark gray'>Обем</span></b>  7 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://mega.nz/'>https://mega.nz/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage megasync nautilus-megasync
      rm -f /etc/yum.repos.d/megasync.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat << EOF > /etc/yum.repos.d/megasync.repo
[MEGAsync]
name=MEGAsync
baseurl=http://mega.nz/linux/MEGAsync/CentOS_7/
gpgkey=https://mega.nz/linux/MEGAsync/CentOS_7/repodata/repomd.xml.key
gpgcheck=1
enabled=1
EOF
      installPackage megasync nautilus-megasync
    fi
  fi
}

install_opera(){
  if isInstalled opera-stable; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Opera Browser" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$opera_Image" --borders=20 \
      --text="<b>Opera Browser (STABLE)</b>
Предоставя повече скорост, повече възможности за откриване на съдържание и повече сигурност в мрежата и всичко това е безплатно.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Web Browser
<b><span color='dark gray'>Хранилище</span></b>  russianfedora-nonfree
<b><span color='dark gray'>Лиценз</span></b>  <a href='http://www.opera.com/bg/eula/computers'>EULA</a>
<b><span color='dark gray'>Обем</span></b>  176,9 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://www.opera.com/bg/computer'>www.opera.com/bg</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage opera-stable opera-stable-libffmpeg chromium-pepper-flash
      rm -f /etc/yum.repos.d/russianfedora-nonfree-updates.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat << EOF > /etc/yum.repos.d/russianfedora-nonfree-updates.repo
[russianfedora-nonfree-updates]
name=Russian Fedora for CentOS $releasever - NonFree - Updates
baseurl=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/el/updates/7/x86_64/
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-russianfedora-nonfree-fedora
exclude=draftsight flash-plugin java-1.7.0-oracle java-1.8.0-oracle rar unrar sublime_text telegram-desktop
EOF
      installPackage opera-stable opera-stable-libffmpeg chromium-pepper-flash
    fi
  fi
}

install_virtualbox() {
  if isInstalled VirtualBox-5.1; then
   BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Oracle VM VirtualBox" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$vbox_Image" --borders=20 \
      --text="<b>Oracle VM VirtualBox</b>
Приложение което може да създава и менажира гостуващи (guest) виртуални машини, всяка с гостуваща операционна система и собствена виртуална среда.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  System → Virtualization
<b><span color='dark gray'>Хранилище</span></b>  virtualbox
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Обем</span></b>  157,4 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.virtualbox.org/'>https://www.virtualbox.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage VirtualBox-5.1
      rm -f /etc/yum.repos.d/virtualbox.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat > /etc/yum.repos.d/virtualbox.repo << EOF_VIRTUALBOX_REPO
[virtualbox]
name=Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
baseurl=http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch
enabled=1
gpgcheck=1
skip_if_unavailable=1
gpgkey=http://www.virtualbox.org/download/oracle_vbox.asc
EOF_VIRTUALBOX_REPO
      installPackage gcc make patch dkms qt libgomp kernel-headers kernel-devel binutils glibc-headers glibc-devel VirtualBox-5.1
      usermod -G vboxusers,vboxsf "$user"
      /usr/lib/virtualbox/vboxdrv.sh setup
    fi
  fi
}

install_flash(){
  if isInstalled flash-plugin; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★☆☆☆☆</span>'
  yad --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$flash_Image" --borders=20 \
      --title="Adobe Flash Player" \
      --text="<b>Adobe Flash Player 24.x</b>
Приложен софтуер, предназначен за създаване на интерактивни мултимедийни приложения.
$stars
<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b> Multimedia
<b><span color='dark gray'>Хранилище</span></b>  adobe-release
<b><span color='dark gray'>Лиценз</span></b>  Commercial
<b><span color='dark gray'>Обем</span></b>  20 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://get.adobe.com/flashplayer/'>https://get.adobe.com/flashplayer/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage adobe-release flash-plugin
      rm -f /etc/yum.repos.d/adobe-linux-x86_64.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
      rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
      installPackage flash-plugin

    fi
  fi
}

install_virtmanager() {
  if isInstalled virt-manager; then
   BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="KVM - Virt Manager" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$virt_Image" \
      --text="<b>KVM - Virt Manager</b>
Графично приложение за управление на виртуални машини за KVM, Xen, и LXC .

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  System → Virtualization
<b><span color='dark gray'>Хранилище</span></b>  Base
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://virt-manager.org/'>http://virt-manager.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client libvirt-daemon-kvm virt-install virt-viewer bridge-utils
      # for libvirtd service
      systemctl stop libvirtd
      systemctl disable libvirtd
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client libvirt-daemon-kvm virt-install virt-viewer bridge-utils
      # for libvirtd service
      systemctl restart libvirtd
      systemctl enable libvirtd
    fi
  fi
}

install_kodi(){
  if isInstalled kodi; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Kodi" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$kodi_Image" --borders=20 \
      --text="<b>Kodi</b>
Крос-медиен плейър, jukebox и център за забавление.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Video → Players
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  GPLv2+ and GPLv3+ and LGPLv2+ and BSD and MIT
<b><span color='dark gray'>Обем</span></b>  42,5 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://kodi.tv/'>https://kodi.tv/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage kodi kodi-pvr-addons-common kodi-pvr-iptvsimple
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage kodi "https://li.nux.ro/download/nux/dextop/el7/x86_64/kodi-pvr-addons-common-14.0-0.2.20150125gita0a437e.el7.nux.noarch.rpm" "https://li.nux.ro/download/nux/dextop/el7/x86_64/kodi-pvr-iptvsimple-14.0-0.2.20150125gita0a437e.el7.nux.x86_64.rpm"
    fi
  fi
}

install_plex(){
  if isInstalled plexmediaserver; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Plex Media Server" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$plex_Image" --borders=20 \
      --text="<b>Plex Media Server</b>
Клиент/сървър система медия плейър.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Media → Server
<b><span color='dark gray'>Лиценз</span></b>  <a href='/usr/share/doc/plexmediaserver/copyright'>copyright</a>
<b><span color='dark gray'>Обем</span></b>  200 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.plex.tv/'>https://www.plex.tv/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage plexmediaserver
       # for plex service
      systemctl stop plexmediaserver
      systemctl disable plexmediaserver
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage "https://downloads.plex.tv/plex-media-server/1.3.3.3148-b38628e/plexmediaserver-1.3.3.3148-b38628e.x86_64.rpm"
      # for plex service
      systemctl enable plexmediaserver
      systemctl start plexmediaserver
      # The following ports are used for different services:
      #
      # TCP: 32400 (for access to the Plex Media Server) [required]
      #
      # UDP: 1900 (for access to the Plex DLNA Server)
      # TCP: 3005 (for controlling Plex Home Theater via Plex Companion)
      # UDP: 5353 (for older Bonjour/Avahi network discovery)
      # TCP: 8324 (for controlling Plex for Roku via Plex Companion)
      # UDP: 32410, 32412, 32413, 32414 (for current GDM network discovery)
      # TCP: 32469 (for access to the Plex DLNA Server
      #
      # Firewalld allow access to the Plex Media Server
      firewall-cmd --zone=public --add-port=32400/tcp --permanent
      firewall-cmd --reload
    fi
  fi
}

install_vivaldi(){
  if isInstalled vivaldi-stable; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Vivaldi" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$vivaldi_Image" --borders=20 \
      --text="<b>Vivaldi</b>
Интернет браузър създаден на базата на Chromium и енджин Blink.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Web Browser
<b><span color='dark gray'>Хранилище</span></b>  vivaldi
<b><span color='dark gray'>Лиценз</span></b>  Multiple, see https://www.vivaldi.com/
<b><span color='dark gray'>Обем</span></b>  165 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://vivaldi.com/?lang=bg'>https://www.vivaldi.com/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage vivaldi-stable
      rm -f /etc/yum.repos.d/vivaldi.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      cat << EOF > /etc/yum.repos.d/vivaldi.repo
[vivaldi]
name=vivaldi
baseurl=http://repo.vivaldi.com/archive/rpm/x86_64
enabled=1
gpgcheck=1
gpgkey=http://repo.vivaldi.com/archive/linux_signing_key.pub
EOF
      installPackage vivaldi-stable
    fi
  fi
}

install_chromium(){
  if isInstalled chromium; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Chromium" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$chromium_image" --borders=20 \
      --text="<b>Chromium</b>
Браузър с отворен код, който има за цел да изгради средство за по-безопасна, по-бърза и по-стабилна употреба на Интернет.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Internet → Web Browser
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  BSD and LGPLv2+
<b><span color='dark gray'>Обем</span></b>  118,7 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.chromium.org/Home'>https://www.chromium.org</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage chromium chromium-pepper-flash chromium-widevinecdm-plugin
      rm -f /etc/yum.repos.d/chromium.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage chromium chromium-pepper-flash chromium-widevinecdm-plugin
      # fix plugins
      cp -R /usr/lib64/chromium/PepperFlash /usr/lib64/chromium-browser
      cp /usr/lib64/chromium/{libwidevinecdmadapter.so,libwidevinecdm.so} /usr/lib64/chromium-browser/
    fi
  fi
}

install_brackets(){
  if isInstalled brackets; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Brackets" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$brackets_Image" --borders=20 \
      --text="<b>Brackets</b>
Отворен код редактор за уеб дизайн и разработка, изградени по технологии като HTML, CSS и JavaScript.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Utilities → Text Editor
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/MIT.html'>MIT</a>
<b><span color='dark gray'>Обем</span></b>  145 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://brackets.io/'>http://brackets.io/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage brackets
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage brackets
    fi
  fi
}

install_syncthing(){
  if isInstalled syncthing; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Syncthing" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$syncthing_Image" --borders=20 \
      --text="<b>Syncthing</b>
Безплатно приложение за синхронизация на файлове между локални мрежи и мрежи в интернет.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b> Utilities → Internet
<b><span color='dark gray'>Хранилище</span></b>  decathorpe-syncthing
<b><span color='dark gray'>Лиценз</span></b> GPLv2
<b><span color='dark gray'>Обем</span></b> 17 MB
<b><span color='dark gray'>Уеб сайт</span></b> <a href='https://syncthing.net/'>https://syncthing.net/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage syncthing syncthing-gtk
      rm -f /etc/yum.repos.d/decathorpe-syncthing-epel-7.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      yum-config-manager --add-repo="https://copr.fedorainfracloud.org/coprs/decathorpe/syncthing/repo/epel-7/decathorpe-syncthing-epel-7.repo"
      installPackage syncthing syncthing-gtk
      # start/enable systemd service
      systemctl start syncthing@"$user".service
      systemctl enable syncthing@"$user".service
    fi
  fi
}

install_terminix(){
  if isInstalled terminix; then
    BtStatus="Премахни"
  else
    BtStatus="Инсталирай"
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Terminix" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$terminix_Image" --borders=20 \
      --text="<b>Terminix</b>
Усъвършенстван GTK3 терминален емулатор за Linux.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Utilities → System
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  MPLv2.0
<b><span color='dark gray'>Обем</span></b>  16 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://github.com/gnunn1/terminix'>https://github.com/gnunn1/terminix</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage terminix terminix-nautilus
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage terminix terminix-nautilus
    fi
  fi
}

install_vscode() {
  if isInstalled code; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Visual Studio Code" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$vscode_Image" --borders=20 \
      --text="<b>Visual Studio Code</b>
Отворен код редактор разработен от Microsoft за Windows, Linux и MacOS.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Utilities → Text Editor
<b><span color='dark gray'>Хранилище</span></b>  code
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://code.visualstudio.com/license'>Multiple</a>
<b><span color='dark gray'>Обем</span></b>  150 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://code.visualstudio.com/'>https://code.visualstudio.com/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage code
      rm -f /etc/yum.repos.d/vscode.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
      rpm --import "https://packages.microsoft.com/keys/microsoft.asc"
      sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
      installPackage "code"
    fi
  fi
}

# The installation menu
menu(){
  while (true); do
    choise=$(yad --title="Инсталиране на приложения" --name="$prog" --text="Изберете приложение което искате да инсталирате, след това щракнете върху бутона <b>OK</b>.\nМоже да сортирате по <b>Име</b> и <b>Категория</b> като щракнете върху заглавието на съответната колона." \
                 --window-icon="$window_icon" \
                 --width="1050" --height="630" --center \
                 --list --print-column=2 \
                 --column=:IMG --column=Име:TEXT --column=Категория:TEXT --column=Описание:TEXT \
                 --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
                 "$steamIcon"  "<b>Steam</b>" "Games" "Инсталатор на Steam клиент" \
                 "$dropboxIcon" "<b>Dropbox</b>" "File Transfer" "Синхронизирайте файлове между компютри в интернет" \
                 "$chromeIcon" "<b>Google Chrome</b>" "Web Browser" "Безплатен уеб браузър на компанията Google" \
                 "$gtalkIcon" "<b>Google Talk Plugin</b>" "Instant Messaging" "Провеждайте гласови и видеоразговори от компютъра си" \
                 "$operaIcon" "<b>Opera Browser (STABLE)</b>" "Web Browser" "Бърз, безопасен и лесен за използване браузър" \
                 "$spotifyIcon" "<b>Spotify Client</b>" "Multimedia" "Spotify клиент за стрийминг на музика" \
                 "$flashIcon" "<b>Adobe Flash Player</b>" "Multimedia" "Плъгин за браузъра който позволява показване на флаш медиа" \
                 "$sublimetextIcon" "<b>Sublime Text 3</b>" "Text Editor" "Приятен за работа редактор за текст и код" \
                 "$atomIcon" "<b>Atom Text Editor</b>" "Text Editor" "Свободен и отворен код текстов редактор за OS X, Linux и Windows" \
                 "$skypeIcon" "<b>Skype</b>" "Instant Messaging" "Приложен софтуер за чат, VOIP телефония и видеовръзка" \
                 "$vboxIcon" "<b>VirtualBox</b>" "Virtualization" "Програма за създаване на виртуални машини" \
                 "$ramboxIcon" "<b>Rambox</b>" "Instant Messaging" "Безплатна, с отворен код платформа за съобщения и имейл приложение" \
                 "$teamvIcon" "<b>TeamViewer</b>" "Internet" "Безплатен отдалечен достъп и отдалечено споделяне на работния плот по Интернет" \
                 "$torIcon" "<b>Tor Browser Launcher</b>" "Web Browser" "Инсталиране и стартиране на Tor браузъра в Linux" \
                 "$megaIcon" "<b>MEGASync Client</b>" "File Transfer" "Интегрира облак услугата MEGA със GNOME десктопа" \
                 "$msIcon" "<b>Msttcorefonts installer</b>" "Fonts" "Инсталатор на Microsoft TrueType шрифтове" \
                 "$telegramIcon" "<b>Telegram</b>" "Instant Messaging" "Приложение за съобщения с акцент върху скоростта и сигурността" \
                 "$virtIcon" "<b>Virt Manager</b>" "Virtualization" "Графично приложение за управление на виртуални машини за KVM, Xen, и LXC" \
                 "$playonlinuxIcon" "<b>PlayOnLinux</b>" "Games" "Инсталира Windows видео игри, Microsoft Office и др." \
                 "$kodiIcon" "<b>Kodi</b>" "Multimedia" "Крос-медиен плейър, jukebox и център за забавление" \
                 "$vivaldiIcon" "<b>Vivaldi</b>" "Web Browser" "Интернет браузър създаден на базата на Chromium и енджин Blink" \
                 "$chromiumIcon" "<b>Chromium</b>" "Web Browser" "Open source версията на Chrome уеб браузъра" \
                 "$bracketsIcon" "<b>Brackets</b>" "Text Editor" "Отворен код редактор за уеб дизайн и разработка" \
                 "$viberIcon" "<b>Viber</b>" "Instant Messaging" "Безплатни разговори, обмен на съобщения и файлове с всеки, и навсякъде" \
                 "$syncthingIcon" "<b>Syncthing</b>" "File Transfer" "Безплатно приложение за синхронизация на файлове" \
                 "$terminixIcon" "<b>Terminix</b>" "System" "GTK 3 Терминал емулатор за Linux" \
                 "$plexIcon" "<b>Plex Media Server</b>" "Multimedia" "Клиент/сървър система медия плейър" \
                 "$ownCloudIcon" "<b>Owncloud-client</b>" "File Transfer" "ownCloud десктоп клиент за синхронизация" \
                 "$vscodeIcon" "<b>Visual Studio Code</b>" "Text Editor" "Редактор разработен от Microsoft за Windows, Linux и MacOS"
          );

    case ${choise} in
      *"Adobe Flash Player"*)install_flash ;;
      *"Steam"*)install_steam ;;
      *"Dropbox"*)install_dropbox ;;
      *"Google Chrome"*)install_chrome ;;
      *"Google Talk Plugin"*)install_gtalk ;;
      *"Opera Browser (STABLE)"*)install_opera ;;
      *"Spotify Client"*)install_spotify ;;
      *"Sublime Text 3"*)install_sublimetext ;;
      *"Owncloud-client"*)install_ownCloud_client ;;
      *"Atom Text Editor"*)install_atom ;;
      *"Skype"*)install_skype ;;
      *"Viber"*)install_viber ;;
      *"Rambox"*)install_rambox ;;
      *"Telegram"*)install_telegram ;;
      *"TeamViewer"*)install_teamviewer ;;
      *"Tor Browser Launcher"*)install_tor ;;
      *"MEGASync Client"*)install_megasync ;;
      *"Msttcorefonts"*)install_mscorefonts ;;
      *"PlayOnLinux"*)install_playonlinux ;;
      *"Kodi"*)install_kodi ;;
      *"Vivaldi"*)install_vivaldi ;;
      *"Chromium"*)install_chromium ;;
      *"Brackets"*)install_brackets ;;
      *"Syncthing"*)install_syncthing ;;
      *"Terminix"*)install_terminix ;;
      *"Plex Media Server"*)install_plex ;;
      *"VirtualBox"*)install_virtualbox ;;
      *"Virt Manager"*)install_virtmanager ;;
      *"Visual Studio Code"*)install_vscode ;;
      *) break ;;
    esac
  done
}

menu
