#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global

install_kde() {
  if isInstalled konsole kde-runtime kde-base-artwork kde-workspace; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Kde" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$kde_Image" --borders=20 \
      --text="<b>KDE</b>
Графична среда с отворен код, използвана главно за UNIX системи, ГНУ/Линукс и др.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Base
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://bg.wikipedia.org/wiki/GNU_General_Public_License'>GPL</a>
<b><span color='dark gray'>Обем</span></b>  430 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.kde.org/'>https://www.kde.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage @kde-desktop @kde-apps @kde-media
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage @kde-desktop @kde-apps @kde-media
    fi
  fi
}

install_xfce() {
  if isInstalled xfce4-session; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Xfce" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$xfce_Image" --borders=20 \
      --text="<b>XFCE</b>
Лека графична среда за UNIX и UNIX-подобни платформи.
Девизът на нейните разработчици е Еволюция без революция.

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  GPL or BSDL
<b><span color='dark gray'>Обем</span></b>  12 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://www.xfce.org/'>http://www.xfce.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage @xfce
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage @xfce
    fi
  fi
}

install_cinnamon() {
  if isInstalled cinnamon; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Cinammon" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$cinnamon_Image" --borders=20 \
      --text="<b>CINNAMON</b>
Графична среда базирана на GTK+ 3 и Gnome Shell

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  <a href='https://spdx.org/licenses/GPL-2.0'>GPLv2</a>
<b><span color='dark gray'>Обем</span></b>  27 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://github.com/linuxmint/Cinnamon'>https://github.com/linuxmint/Cinnamon</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage cinnamon
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage cinnamon
    fi
  fi
}

install_mate() {
  if isInstalled mate-desktop marco; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★★☆</span>'
  yad --title="Mate" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$mate_Image" --borders=20 \
      --text="<b>MATE</b>
Графична среда базирана на кода на вече неподържаната работна среда GNOME 2

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  GNU LGPL, GNU GPL
<b><span color='dark gray'>Обем</span></b>  185 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://mate-desktop.org/'>http://mate-desktop.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage @mate
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage @mate
    fi
  fi
}

install_lxde() {
  if isInstalled lxde-common; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Lxde" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$lxde_Image" --borders=20 \
      --text="<b>LXDE</b>
Лека графична среда за Gnu/Linux

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  StotinkaOS-Base
<b><span color='dark gray'>Лиценз</span></b>  GPL/LGPL
<b><span color='dark gray'>Обем</span></b>  12 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://lxde.org/'>http://lxde.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage lxde-common lxpanel lxsession-lite openbox pcmanfm lxappearance lxterminal lxinput lxpolkit lxde-icon-theme lxmusic lxtask lxrandr gpicview leafpad obconf
    elif [[ "$BtStatus" == Инсталирай ]]; then
      # fix http://www.stotinkaos.net/forums/thread-576-post-5698.html
      # conflict with the package libfm-1.2.4 from EPEL repo
      sed -i '9i exclude=libfm*' /etc/yum.repos.d/epel.repo
      installPackage lxde-common lxpanel lxsession-lite openbox pcmanfm lxappearance lxterminal lxinput lxpolkit lxde-icon-theme lxmusic lxtask lxrandr gpicview leafpad obconf
    fi
  fi
}

install_lxqt() {
  if isInstalled lxqt-common; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★★☆☆</span>'
  yad --title="Lxqt" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$lxqt_Image" --borders=20 \
      --text="<b>LXQT</b>
Графична среда формирана в резултат на сливането на LXDE и Razor-qt

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  GNU GPL, GNU LGPL
<b><span color='dark gray'>Обем</span></b>  44 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='http://lxqt.org/'>http://lxqt.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage lxqt-"*" pcmanfm-qt openbox qterminal-qt5
    elif [[ "$BtStatus" == Инсталирай ]]; then
      # fix http://www.stotinkaos.net/forums/thread-576-post-5698.html
      # conflict with the package libfm-1.2.3 from StotinkaOS-Base repo
      sed -i '/exclude=libfm*/d' /etc/yum.repos.d/epel.repo
      installPackage lxqt-"*" pcmanfm-qt openbox qterminal-qt5
    fi
  fi
}

install_tde() {
  if isInstalled trinity-desktop; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Tde" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$tde_Image" --borders=20 \
      --text="<b>TDE (Trinity Desktop Environment)</b>
Графична среда базирана на кода на вече неподържаната работна среда KDE 3.5

$stars
<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  trinity-r14
<b><span color='dark gray'>Лиценз</span></b>  GPL
<b><span color='dark gray'>Обем</span></b>  600 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://www.trinitydesktop.org/index.php'>https://www.trinitydesktop.org/index.php</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage trinity-desktop trinity-tde-i18n-Bulgarian trinity-koffice-i18n-Bulgarian
      rm -f /etc/yum.repos.d/trinity.repo
    elif [[ "$BtStatus" == Инсталирай ]]; then
cat << EOF > /etc/yum.repos.d/trinity.repo
[trinity-r14]
name=trinity-r14
baseurl=https://ftp.fau.de/trinity/trinity/rpm/el7/trinity-r14/RPMS/x86_64/
#mirrorlist=http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el7/trinity-r14-$basearch.list
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-trinity

[trinity-r14-noarch]
name=trinity-r14-noarch
baseurl=https://ftp.fau.de/trinity/trinity/rpm/el7/trinity-r14/RPMS/noarch
#mirrorlist=http://mirror.ppa.trinitydesktop.org/trinity/trinity/rpm/el7/trinity-r14-noarch.list
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-trinity
EOF
     installPackage trinity-desktop trinity-tde-i18n-Bulgarian trinity-koffice-i18n-Bulgarian
    fi
  fi
}

install_lumina() {
  if isInstalled lumina-desktop; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  stars='<span size="xx-large">★★☆☆☆</span>'
  yad --title="Lumina" --width="1100" --height="480" \
      --window-icon="$window_icon" \
      --image="$lumina_Image" --borders=20 \
      --text="<b>Lumina</b>
Лека графична среда предназначена за Unix-подобни операционни системи .

$stars

<b>Детайли</b>
<b><span color='dark gray'>Категория</span></b>  Desktop environment
<b><span color='dark gray'>Хранилище</span></b>  Epel
<b><span color='dark gray'>Лиценз</span></b>  BSD
<b><span color='dark gray'>Обем</span></b>  70 MB
<b><span color='dark gray'>Уеб сайт</span></b>  <a href='https://lumina-desktop.org/'>https://lumina-desktop.org/</a>" \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage lumina-desktop lumina-desktop-wallpapers lumina-config lumina-fm lumina-info lumina-open lumina-screenshot lumina-search lumina-textedit lumina-xconfig lumina-fileinfo oxygen-icon-theme
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage lumina-desktop lumina-desktop-wallpapers lumina-config lumina-fm lumina-info lumina-open lumina-screenshot lumina-search lumina-textedit lumina-xconfig lumina-fileinfo oxygen-icon-theme
    fi
  fi
}

# Main menu
menu(){
while :
do
  choise=$(yad --title="Инсталиране на Графична среда" --name="$prog" \
               --window-icon="$window_icon" \
               --width="450" --height="500" --center --fixed \
               --list --print-column=2 \
               --column=:IMG --column "Име":TEXT \
               --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
               "$kdeIcon" "<b>KDE</b>" \
               "$cinnamonIcon" "<b>CINNAMON</b>" \
               "$mateIcon" "<b>MATE</b>" \
               "$xfceIcon" "<b>XFCE</b>" \
               "$lxdeIcon" "<b>LXDE</b>" \
               "$lxqtIcon" "<b>LXQT</b>" \
               "$tdeIcon" "<b>TDE (Trinity)</b>" \
               "$luminaIcon" "<b>Lumina</b>" );

  case ${choise} in
    *"KDE"*)install_kde ;;
    *"CINNAMON"*)install_cinnamon ;;
    *"MATE"*)install_mate ;;
    *"XFCE"*)install_xfce ;;
    *"LXDE"*)install_lxde ;;
    *"LXQT"*)install_lxqt ;;
    *"TDE (Trinity)"*)install_tde  ;;
    *"Lumina"*)install_lumina ;;
    *) break ;;
  esac
done
}

menu
