#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global


do
  choise=$(yad --title="$prog - Клиенти за виртуализация" --name="$prog" \
               --window-icon="$window_icon" \
               --width="450" --height="500" --center --fixed \
               --list --column=:IMG --column=Име:TEXT --column=Описание:TEXT \
               --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
               true 0 "VirtualBox-5.1" \
               false 1 "GNOME Boxes" \
               false 2 "Virt Manager");

  case ${choise} in
    *) break ;;
  esac
done
}

menu
