#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global

if [[ ! -f /tmp/sos-easy-install.log ]]; then
  TMP_LOG=$(yad --text="Няма създаден лог файл $*" \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="Грешка" \
        --image=gtk-dialog-error \
        --center)
  exit
else
  TMP_LOG="/tmp/sos-easy-install.log"
fi

showlog() {
  yad --title="$prog" --text-info --filename="$TMP_LOG" \
      --window-icon="$window_icon" \
      --width="650" --height="400" \
      --button="Затваряне":1 \
      --selectable-labels \
      --center
}

showlog
