#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

# Global
prog="sos-easy-install"
ver=4.0
window_icon="/usr/share/icons/hicolor/96x96/apps/sos-easy-install.png"
image_icon="/usr/share/pixmaps/sosEI-header.png"
app_icon="/usr/share/icons/sos-ei-app-icons"
license="/usr/share/licenses/sos-easy-install/COPYING"
arch=$(uname -m)
user=$(who | cut -d' ' -f1 | sort | uniq);

# Applications

# steam
steamIcon="/usr/share/icons/Moka/24x24/apps/steam.png"
steam_Image="$app_icon/steam_image.png"
# dropbox
dropboxIcon="/usr/share/icons/Moka/24x24/apps/dropbox.png"
dropbox_Image="$app_icon/dropbox_image.png"
# chrome
chromeIcon="/usr/share/icons/Moka/24x24/apps/google-chrome-stable.png"
chrome_Image="$app_icon/chrome_image.png"
# msfonts
msIcon="$app_icon/ms-fonts.png"
ms_Image="$app_icon/msttcorefonts_image.png"
# playonlinux
playonlinuxIcon="/usr/share/icons/Moka/24x24/apps/playonlinux.png"
playonlinux_Image="$app_icon/playonlinux_image.png"
# skype
skypeIcon="/usr/share/icons/Moka/24x24/apps/skype.png"
skype_Image="$app_icon/skype_image.png"
# teamviewer
teamvIcon="/usr/share/icons/Moka/24x24/apps/teamviewer.png"
teamv_Image="$app_icon/teamv_image.png"
# viber
viberIcon="/usr/share/icons/Moka/24x24/web/web-viber.png"
viber_Image="$app_icon/viber_image.png"
# virtualbox
vboxIcon="/usr/share/icons/Moka/24x24/apps/virtualbox.png"
vbox_Image="$app_icon/virtualbox_image.png"
# sudo
sudoIcon="$app_icon/sudo.png"
# selinux
selinuxIcon="$app_icon/selinux.png"
# gtalk plugin
gtalkIcon="$app_icon/gtalk.png"
gtalk_Image="$app_icon/gtalk_image.png"
# tor brower
torIcon="$app_icon/tor.png"
tor_Image="$app_icon/tor_image.png"
# spotify
spotifyIcon="/usr/share/icons/Moka/24x24/web/spotify-client.png"
spotify_Image="$app_icon/spotify_image.png"
# sublime
sublimetextIcon="/usr/share/icons/Moka/24x24/apps/sublimetext.png"
sublimetext_Image="$app_icon/sublimetext_image.png"
# atom
atomIcon="/usr/share/icons/Moka/24x24/apps/atom.png"
atom_Image="$app_icon/atom_image.png"
# mega
megaIcon="/usr/share/icons/Moka/24x24/apps/mega.png"
mega_Image="$app_icon/mega_image.png"
# flash
flashIcon="/usr/share/icons/Moka/24x24/apps/adobe-flashplayer.png"
flash_Image="$app_icon/adobeflash_image.jpg"
# opera
operaIcon="/usr/share/icons/Moka/24x24/apps/opera.png"
opera_Image="$app_icon/opera_image.png"
# rambox
ramboxIcon="$app_icon/rambox.png"
rambox_Image="$app_icon/rambox_image.png"
# telegram
telegramIcon="/usr/share/icons/Moka/24x24/web/telegram.png"
telegram_Image="$app_icon/telegram_image.png"
# kodi
kodiIcon="/usr/share/icons/Moka/24x24/apps/kodi.png"
kodi_Image="$app_icon/kodi_image.jpg"
# vivaldi
vivaldiIcon="/usr/share/icons/Moka/24x24/apps/vivaldi.png"
vivaldi_Image="$app_icon/vivaldi_image.png"
# chromium
chromiumIcon="/usr/share/icons/Moka/24x24/apps/chromium.png"
chromium_image="$app_icon/chromium_image.png"
# brackets
bracketsIcon="/usr/share/icons/Moka/24x24/apps/brackets.png"
brackets_Image="$app_icon/brackets_image.png"
# kernel-ml
kernelIcon="$app_icon/kernel.png"
# syncthing
syncthingIcon="/usr/share/icons/Moka/24x24/apps/syncthing-gtk.png"
syncthing_Image="$app_icon/syncthing_image.png"
# terminix
terminixIcon="/usr/share/icons/Moka/24x24/apps/terminix.png"
terminix_Image="$app_icon/terminix_image.png"
# virt-manager
virtIcon="/usr/share/icons/Moka/24x24/apps/virt-manager.png"
virt_Image="$app_icon/virt-manager_image.png"
# plex
plexIcon="/usr/share/icons/Moka/24x24/apps/plex.png"
plex_Image="$app_icon/plex_image.png"
# ownCloud client
ownCloudIcon="/usr/share/icons/Moka/24x24/apps/owncloud.png"
ownCloud_Image="$app_icon/ownCloud_image.png"
# vscode
vscodeIcon="/usr/share/icons/Moka/24x24/apps/visual-studio-code.png"
vscode_Image="$app_icon/vscode_Image.png"
# brave
braveIcon="/usr/share/icons/Moka/24x24/apps/brave.png"
brave_Image="$app_icon/brave_Image.png"
# master-pdf-editor
masterpdfIcon="$app_icon/masterpdfIcon.png"
masterpdf_Image="$app_icon/masterpdf_Image.png"
# wps office
wpsIcon="/usr/share/icons/Moka/24x24/apps/wps-office-wpsmain.png"
wps_Image="$app_icon/wps_Image.png"

# Desktop env icons

# kde
kdeIcon="$app_icon/kde.png"
kde_Image="$app_icon/kde_image.png"
# xfce
xfceIcon="$app_icon/xfce.png"
xfce_Image="$app_icon/xfce_image.jpg"
# mate
mateIcon="$app_icon/mate.png"
mate_Image="$app_icon/mate_image.png"
# cinnamon
cinnamonIcon="$app_icon/cinnamon.png"
cinnamon_Image="$app_icon/cinnamon_image.png"
# lxde
lxdeIcon="$app_icon/lxde.png"
lxde_Image="$app_icon/lxde_image.png"
# lxqt
lxqtIcon="$app_icon/lxqt.png"
lxqt_Image="$app_icon/lxqt_image.png"
# tde
tdeIcon="$app_icon/tde.png"
tde_Image="$app_icon/tde_image.png"
# lumina
luminaIcon="$app_icon/lumina.png"
lumina_Image="$app_icon/lumina_image.png"

# Log last activities to retrieve errors
TMP_LOG="/tmp/sos-easy-install.log"

## Functions

# Checking user's privileges
if [[ $EUID -ne 0 ]]; then
  yad --text="ГРЕШКА:Програмата трябва да се стартира с права на потребител <b>root</b>!" \
      --window-icon="$window_icon" \
      --title="$prog" \
      --width="450" --height="200" \
      --image=gtk-dialog-error \
      --button="Затваряне!gtk-close":1 \
      --center
  exit 1
fi

# Notify message
notifyUser(){
  yad --title="$prog" --window-icon="$window_icon" --image=gtk-dialog-info --button="ОК!gtk-ok":1 --text="$1" --width=450 --center
}

# Kill off any package managers that may be running
if [[ "$(pgrep gnome-software)" || "$(pgrep yumex)" || "$(pgrep yum)" ]]; then
    if yad --title="$prog" --window-icon="$window_icon" \
           --text="<b>YUM</b> Мениджъра на пакети работи. Искате ли да го затворите?" \
           --width="450" --height="200" \
           --image=dialog-question \
           --button="Да":0 --button="Не":1 \
           --center ; then
      killall -9 gnome-software yumex yum
    else
      notifyUser "Изход от програмата!"
      exit 0
    fi
fi

# Checking installed packages
isInstalled(){
  rpm -q --quiet "$@"
}

# Check if yum install success
checkInstallSuccess(){
  yum --nogpgcheck install -y "$@" 2>&1

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    yad --text="Грешка при инсталиране на $*
Проверете файла <b>/tmp/sos-easy-install.log</b> за подробна информация!" \
        --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
    notifyUser "Инсталирането на $* приключи успешно"
  fi
}

# Install package
installPackage(){
  checkInstallSuccess "$@" | tee $TMP_LOG | stdbuf -oL sed -n 's/^/# /p' | yad --title="Инсталиране на $*" \
                            --text='Моля изчакайте....' \
                            --height=250 --width=500 \
                            --no-escape --progress --pulsate --enable-log="Детайли" --log-height=600 --auto-close \
                            --window-icon="$window_icon" \
                            --no-buttons \
                            --image=system-software-install \
                            --center
}

# Check if yum remove success
checkRemoveSuccess(){
  yum remove -y --setopt clean_requirements_on_remove=1 "$@" 2>&1

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    yad --text="Грешка при премахване на $*" \
        --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
     notifyUser "Пакета $* е успешно премахнат"
  fi
}

# Remove installed packages
removePackage(){
   checkRemoveSuccess "$@" | tee $TMP_LOG | stdbuf -oL sed -n 's/^/# /p' | yad --title="Премахване на $*" \
                             --text='Моля изчакайте....' \
                             --height=250 --width=500 \
                             --no-escape --progress --pulsate --enable-log="Детайли" --log-height=600 --auto-close \
                             --window-icon="$window_icon" \
                             --no-buttons \
                             --image=gtk-remove \
                             --center
}
