#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

# Global
prog="sos-easy-install"
ver=3.8
window_icon="/usr/share/icons/hicolor/96x96/apps/sos-easy-install.png"
image_icon="/usr/share/pixmaps/sosEI-header.png"
app_icon="/usr/share/icons/sos-ei-app-icons"
license="/usr/share/licenses/sos-easy-install/COPYING"
arch=$(uname -m)
user=$(who | cut -d' ' -f1 | sort | uniq);

# Applications
steamIcon="$app_icon/steam1.png"
dropboxIcon="$app_icon/dropbox.png"
chromeIcon="$app_icon/chrome.png"
msIcon="$app_icon/ms-fonts.png"
playonlinuxIcon="$app_icon/playonlinux.png"
skypeIcon="$app_icon/skype.png"
teamvIcon="$app_icon/teamviewer.png"
viberIcon="$app_icon/viber.png"
vboxIcon="$app_icon/virtualbox.png"
sudoIcon="$app_icon/sudo.png"
selinuxIcon="$app_icon/selinux.png"
gtalkIcon="$app_icon/gtalk.png"
torIcon="$app_icon/tor.png"
spotifyIcon="$app_icon/spotify.png"
sublimetextIcon="$app_icon/sublimetext.png"
atomIcon="$app_icon/atom.png"
loginIcon="$app_icon/autologin.png"
megaIcon="$app_icon/mega.png"
flashIcon="$app_icon/flash.png"
operaIcon="$app_icon/opera.png"
telegramIcon="$app_icon/telegram.png"
kodiIcon="$app_icon/kodiIcon.png"
vivaldiIcon="$app_icon/vivaldi.png"
chromiumIcon="$app_icon/chromium.png"
bracketsIcon="$app_icon/brackets.png"
kernelIcon="$app_icon/kernel.png"
syncthingIcon="$app_icon/syncthing.png"
terminixIcon="$app_icon/terminix.png"
boxesIcon="$app_icon/gnome-boxes.png"
virtIcon="$app_icon/virt-manager.png"
plexIcon="$app_icon/plex.png"

# Desktop
kdeIcon="$app_icon/kde.png"
xfceIcon="$app_icon/xfce.png"
mateIcon="$app_icon/mate.png"
cinnamonIcon="$app_icon/cinnamon.png"
lxdeIcon="$app_icon/lxde.png"
lxqtIcon="$app_icon/lxqt.png"
tdeIcon="$app_icon/tde.png"
luminaIcon="$app_icon/lumina.png"

# Log last activities to retrieve errors
TMP_LOG="/tmp/sos-easy-install.log"

## Functions

# Checking user's privileges
if [[ $EUID -ne 0 ]]; then
  yad --text="ГРЕШКА:Програмата трябва да се стартира с права на потребител <b>root</b>!" \
      --window-icon="$window_icon" \
      --title="$prog" \
      --width="450" --height="200" \
      --image=gtk-dialog-error \
      --button="Затваряне!gtk-close":1 \
      --center
  exit 1
fi

# Notify message
notifyUser(){
  yad --title="$prog" --window-icon="$window_icon" --image=gtk-dialog-info --button="ОК!gtk-ok":1 --text="$1" --width=450 --center
}

# Kill off any package managers that may be running
if [[ "$(pgrep gnome-software)" || "$(pgrep yumex)" || "$(pgrep yum)" ]]; then
    if yad --title="$prog" --window-icon="$window_icon" \
           --text="<b>YUM</b> Мениджъра на пакети работи. Искате ли да го затворите?" \
           --width="450" --height="200" \
           --image=dialog-question \
           --button="Да":0 --button="Не":1 \
           --center ; then
      killall -9 gnome-software yumex yum
    else
      notifyUser "Изход от програмата!"
      exit 0
    fi
fi

# Checking installed packages
isInstalled(){
  rpm -q --quiet "$@"
}

# Check if yum install success
checkInstallSuccess(){
  yum --nogpgcheck install -y "$@" 2>&1

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    yad --text="Грешка при инсталиране на $*
Проверете файла <b>/tmp/sos-easy-install.log</b> за подробна информация!" \
        --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
    notifyUser "Инсталирането на $* приключи успешно"
  fi
}

# Install package
installPackage(){
  checkInstallSuccess "$@" | tee $TMP_LOG | stdbuf -oL sed -n 's/^/# /p' | yad --title="Инсталиране на $*" \
                            --text='Моля изчакайте....' \
                            --height=250 --width=500 \
                            --no-escape --progress --pulsate --enable-log="Детайли" --log-height=600 --auto-close \
                            --window-icon="$window_icon" \
                            --no-buttons \
                            --image=system-software-install \
                            --center
}

# Check if yum remove success
checkRemoveSuccess(){
  yum remove -y --setopt clean_requirements_on_remove=1 "$@" 2>&1

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    yad --text="Грешка при премахване на $*" \
        --button="ОК!gtk-ok":0 --button="Затваряне!gtk-close":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
     notifyUser "Пакета $* е успешно премахнат"
  fi
}

# Remove installed packages
removePackage(){
   checkRemoveSuccess "$@" | tee $TMP_LOG | stdbuf -oL sed -n 's/^/# /p' | yad --title="Премахване на $*" \
                             --text='Моля изчакайте....' \
                             --height=250 --width=500 \
                             --no-escape --progress --pulsate --enable-log="Детайли" --log-height=600 --auto-close \
                             --window-icon="$window_icon" \
                             --no-buttons \
                             --image=gtk-remove \
                             --center
}
