#!/bin/bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

source /usr/bin/sos-easy-install-plugins/global

# Show about dialog
info() {
  yad --title="$prog" --selectable-labels --text-align=left --text="<span font_weight='bold' font='17'>$prog $ver </span>\n\n\Програма, която ви позволява да инсталирате допълнителен софтуер като Skype, Chrome, Steam и др., също така, дава възможност да настройте допълнително вашата StotinkaOS, само с няколко щраквания на мишката.   \n\n<span font='9'>Copyright © 2015-2016 StotinkaOS Team\nwebsite: <a href='http://stotinkaos.net'>http://stotinkaos.net</a></span>" \
      --window-icon="$window_icon" \
      --width="600" --height="300" \
      --button="ОК":0 --button="Лиценз":2 --button="Затваряне":1 \
      --image="$window_icon" \
      --center
  ret=$?

  if [[ "$ret" -eq "2" ]]; then
    yad --title="$prog" --text-info --filename="$license" \
        --window-icon="$window_icon" \
        --width="500" --height="300" \
        --button="Затваряне":1 \
        --center
  fi
  menu
}

menu(){
yad --center --icons --name="sos-easy-install - Меню" --window-icon="$window_icon" --width=750 --height=450 --read-dir="/usr/bin/sos-easy-install-plugins/menu" --item-width=100 --single-click --sort-by-name --title="sos-easy-install - Меню" --button="gtk-about":2 --button="Затваряне":1

ret=$?

  if [[ "$ret" -eq "2" ]]; then
    info
  fi
}

menu
