#!/bin/env bash

<<"COMMENT"
Copyright (C) 2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

## General

prog="${0##*/}"
ver=2.4
window_icon="/usr/share/icons/hicolor/96x96/apps/sos-easy-install.png"
image_icon="/usr/share/pixmaps/sosEI-header.png"
license="/usr/share/licenses/sos-easy-install/COPYING"
arch=$(uname -m)
user=$(who | cut -d' ' -f1 | sort | uniq);

steamIcon="/usr/share/icons/sos-ei-app-icons/steam1.png"
dropboxIcon="/usr/share/icons/sos-ei-app-icons/dropbox.png"
chromeIcon="/usr/share/icons/sos-ei-app-icons/chrome.png"
msIcon="/usr/share/icons/sos-ei-app-icons/ms-fonts.png"
playonlinuxIcon="/usr/share/icons/sos-ei-app-icons/playonlinux.png"
skypeIcon="/usr/share/icons/sos-ei-app-icons/skype.png"
teamvIcon="/usr/share/icons/sos-ei-app-icons/teamviewer.png"
viberIcon="/usr/share/icons/sos-ei-app-icons/viber.png"
vboxIcon="/usr/share/icons/sos-ei-app-icons/virtualbox.png"
sudoIcon="/usr/share/icons/sos-ei-app-icons/sudo.png"
selinuxIcon="/usr/share/icons/sos-ei-app-icons/selinux.png"
gtalkIcon="/usr/share/icons/sos-ei-app-icons/gtalk.png"
torIcon="/usr/share/icons/sos-ei-app-icons/tor.png"
spotifyIcon="/usr/share/icons/sos-ei-app-icons/spotify.png"
sublimetextIcon="/usr/share/icons/sos-ei-app-icons/sublimetext.png"
atomIcon="/usr/share/icons/sos-ei-app-icons/atom.png"
loginIcon="/usr/share/icons/sos-ei-app-icons/autologin.png"

## Functions

## from version 1.8 is using authentication via PAM
# Checking user's privileges
#if [[ $EUID -ne 0 ]]; then
#  yad --text="Програмата трябва да се стартира с правата на потребител root.\nСтартирайте отново, по следният начин:\n\n<b>su -c '$prog'</b>\nили\n<b>beesu $prog</b>" \
#      --window-icon="$window_icon" \
#      --title="$prog" \
#      --width="450" --height="200" \
#      --button="ОК":0 --button="Затваряне":1 \
#      --selectable-labels \
#      --center
#  exit 1
#fi

# Set up log facilities
# Example output: [02/06/15 20:03:12] message input
LOGFILE=/var/log/sos-easy-install.log
log(){
    message="$@"
    echo '['$(date +%D\ %H:%M:%S)'] '$message >>$LOGFILE
}

# Log last activities to retrieve errors
TMP_LOG=/tmp/sos-easy-install.log

# Notify message
notifyUser(){
  yad --title="$prog" --window-icon="$window_icon" --image=gtk-dialog-info --button="ОК":1 --text="$1" --width=450 --center
}

# Kill off any package managers that may be running
if [[ "$(pgrep yumex)"||"$(pgrep yum)" ]]; then
    if yad --title="$prog" --window-icon="$window_icon" \
           --text="<b>YUM</b> Мениджъра на пакети работи. Искате ли да го затворите?" \
           --width="450" --height="200" \
           --image=dialog-question \
           --button="Да":0 --button="Не":1 \
           --center ; then
      killall -9 yumex yum
    else
      notifyUser "Изход от програмата!"
      log "ERROR:Изход от програмата, YUM пакет мениджъра работи!"
      exit 0
    fi
fi

# Checking installed packages
isInstalled(){
  rpm -q --quiet "$@"
}

# Check if yum install success
checkInstallSuccess(){
  yum --nogpgcheck install -y "$@" 2>&1 | tee $TMP_LOG

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    log "ERROR:Грешка при инсталиране на $*"
    yad --text="Грешка при инсталиране на $*

Проверете файла <b>/tmp/sos-easy-install.log</b> за подробна информация!" \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
    notifyUser "Инсталирането на $* приключи успешно"
    log "INFO:Инсталирането на $* приключи успешно"
  fi
}

# Install package
installPackage(){
  checkInstallSuccess "$@" | yad --title="Инсталиране на $*" \
                            --text='Моля изчакайте....' \
                            --height=250 --width=500 \
                            --progress --pulsate --auto-close --auto-kill \
                            --window-icon="$window_icon" \
                            --no-buttons \
                            --image=system-software-install \
                            --center
}

# Check if yum remove success
checkRemoveSuccess(){
  yum remove -y --setopt clean_requirements_on_remove=1 "$@" 2>&1 | tee $TMP_LOG

  if [ "${PIPESTATUS[0]}" -ne "0" ]; then
    log "ERROR:Грешка при премахване на $*"
    yad --text="Грешка при премахване на $*" \
        --button="ОК":0 --button="Затваряне":1 \
        --window-icon="$window_icon" \
        --title="$prog" \
        --image=gtk-dialog-error \
        --center
    return
  else
     notifyUser "Пакета $* е успешно премахнат"
     log "INFO:Пакета $* е успешно премахнат"
  fi
}

# Remove installed packages
removePackage(){
   checkRemoveSuccess "$@" | yad --title="Премахване на $*" \
                             --text='Моля изчакайте....' \
                             --height=250 --width=500 \
                             --progress --pulsate --auto-close --auto-kill \
                             --window-icon="$window_icon" \
                             --no-buttons \
                             --image=system-software-install \
                             --center
}

install_steam() {
  if isInstalled steam; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$steamIcon" \
      --text="<b>Steam</b>

Най-добрата платформа за онлайн игра.

<b>Лиценз:</b> Steam Лицензионно Споразумение
<b>Уеб сайт на проекта:</b> <a href='http://store.steampowered.com/'>http://store.steampowered.com/</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage steam
    elif [[ "$BtStatus" == Инсталирай ]]; then
      yum-config-manager --add-repo=http://negativo17.org/repos/epel-steam.repo
        cat << EOF > /etc/yum.repos.d/adobe-linux-i386.repo
[adobe-linux-i386]
name=Adobe Systems Incorporated
baseurl=http://linuxdownload.adobe.com/linux/i386/
enabled=1
skip_if_unavailable=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
EOF
        # install steam
        installPackage flash-plugin.i386 flash-plugin.x86_64 steam
        # allow Steam to start in Big Picture mode
        setsebool -P allow_execheap 1
    fi
  fi
}

install_dropbox() {
  if isInstalled nautilus-dropbox; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

 yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$dropboxIcon" \
      --text="<b>Dropbox</b>

Разширение за файловият мениджър Nautilus, което интегрира облак услугата Dropbox със GNOME десктопа.

<b>Лиценз:</b> GPLv3
<b>Уеб сайт на проекта:</b> <a href='https://www.dropbox.com'>https://www.dropbox.com</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage nautilus-dropbox
    elif [[ "$BtStatus" == Инсталирай ]]; then
        # find latest version
      URL=$(wget "https://www.dropbox.com/install?os=lnx" -O - | tr ' ' '\n' | grep -o "nautilus-dropbox-[0-9]*.[0-9]*.[0-9]*-[0-9]*.fedora.x86_64.rpm" | head -n 1 | sed -e 's/^/http:\/\/linux.dropbox.com\/packages\/fedora\//')
      installPackage "$URL"
      rm -f /etc/yum.repos.d/dropbox.repo
    fi
  fi
}

install_viber(){
  if isInstalled viber; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$viberIcon" \
      --text="<b>Viber</b>

Безплатни разговори, обмен на съобщения и файлове с всеки, и навсякъде.

<b>Лиценз:</b> Adware
<b>Уеб сайт на проекта:</b> <a href='http://www.viber.com/en/'>http://www.viber.com/en/</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage viber
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage https://download.cdn.viber.com/desktop/Linux/viber.rpm
      # fix $PATH
      ln -s /opt/viber/Viber /usr/bin/Viber
    fi
  fi
}

install_spotify(){
  if isInstalled spotify-client; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$spotifyIcon" \
      --text="<b>Spotify Client</b>

Дигитална музикална услуга, която ви дава достъп до милиони песни .

<b>Лиценз:</b> <a href='https://www.spotify.com/legal/end-user-agreement'>end-user-agreement</a>
<b>Уеб сайт на проекта:</b> <a href='https://www.spotify.com/bg/'>www.spotify.com/bg/</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage spotify-client
    elif [[ "$BtStatus" == Инсталирай ]]; then
  cat << EOF > /etc/yum.repos.d/epel-spotify.repo
[epel-spotify]
name=negativo17 - Spotify
baseurl=http://negativo17.org/repos/spotify/epel-7/x86_64/
enabled=1
skip_if_unavailable=1
gpgkey=http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
gpgcheck=1
exclude=a52dec faad2 faad2-libs lame lame-libs libdvdcss libdvdnav libdvdread libmad libmpeg2 librtmp x264 x264-libs x265 x265-libs xvidcore ffmpeg ffmpeg-compat gpac rtmpdump
EOF
      installPackage spotify-client
    fi
  fi
}

install_sublimetext(){
  if isInstalled sublime_text; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$sublimetextIcon" \
      --text="<b>Sublime Text 3</b>

Приятен за работа редактор за текст и код .

<b>Лиценз:</b> EULA
<b>Уеб сайт на проекта:</b> <a href='https://www.sublimetext.com/3'>www.sublimetext.com/3</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage sublime_text
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage sublime_text
    fi
  fi
}

install_atom() {
  if isInstalled atom; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$atomIcon" \
      --text="<b>Atom Text Editor</b>

Свободен и отворен код текстов редактор за OS X, Linux и Windows с поддръжка на плъгини разработен от github.

<b>Лиценз:</b> MIT
<b>Уеб сайт на проекта:</b> <a href='https://atom.io/'>https://atom.io/</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage atom
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage "https://github.com/atom/atom/releases/download/v1.6.0/atom.x86_64.rpm"
    fi
  fi
}

install_gtalk() {
  if isInstalled google-talkplugin; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=480 \
      --window-icon="$window_icon" \
      --image="$gtalkIcon" \
      --text="<b>Google Talk Plugin</b>

Плъгин за браузъра, който позволява да се правят гласови и видео-чат разговори с приятели чрез уеб камера и микрофон, свързан към компютър.

<b>Лиценз:</b> Безплатна програма, Google условия за ползване на услугата.
<b>Уеб сайт на проекта:</b> <a href='www.google.com/chat/video'>www.google.com/chat/video</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage google-talkplugin
    elif [[ "$BtStatus" == Инсталирай ]]; then
cat << EOF > /etc/yum.repos.d/google-talkplugin.repo
[google-talkplugin]
name=google-talkplugin
baseurl=http://dl.google.com/linux/talkplugin/rpm/stable/x86_64
enabled=1
gpgcheck=1
skip_if_unavailable=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-google-talkplugin
EOF
      installPackage google-talkplugin
    fi
  fi
}

install_chrome() {
  if isInstalled google-chrome-stable; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$chromeIcon" \
      --text="<b>Google Chrome</b>

Бърз, лесен и защитен уеб браузър, изграден за модерният уеб.

<b>Лиценз:</b> Безплатна програма, Google Chrome условия за ползване на услугата.
<b>Уеб сайт на проекта:</b> <a href='https://www.google.com/chrome/'>https://www.google.com/chrome</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage google-chrome-stable
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage google-chrome-stable
    fi
  fi
}

install_skype() {
  if isInstalled skype; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

 yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$skypeIcon" \
      --text="<b>Skype</b>

Приложен софтуер за чат, VOIP телефония и видеовръзка.

<b>Лиценз:</b> Собственически лиценз, Безплатен софтуер с допълнителни, платени възможности.
<b>Уеб сайт на проекта:</b> <a href='https://www.skype.com/'>https://www.skype.com</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
 ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage skype
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage skype
    fi
  fi
}

install_virtualbox() {
  if isInstalled VirtualBox-5.0; then
   BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$vboxIcon" \
      --text="<b>VirtualBox</b>

VirtualBox създава виртуална среда, в която може да инсталирате различни операционни системи, да инсталирате и тествате програми или с други думи може да правите почти всичко, което правите в нормалната ви ОС, без да се притеснявате, че може да повредите нещо.

<b>Лиценз:</b> GPLv2
<b>Уеб сайт на проекта:</b> <a href='https://www.virtualbox.org/'>https://www.virtualbox.org/</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage VirtualBox-5.0
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage gcc make patch dkms qt libgomp kernel-headers kernel-devel binutils glibc-headers glibc-devel VirtualBox-5.0
      usermod -G vboxusers,vboxsf "$user"
      /usr/lib/virtualbox/vboxdrv.sh setup
    fi
  fi
}

install_teamviewer() {
  if isInstalled teamviewer; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$teamvIcon" \
      --text="<b>TeamViewer</b>

Безплатен отдалечен достъп и отдалечено споделяне на работния плот по Интернет.

<b>Лиценз:</b> Патентован, безплатен за некомерсиална употреба.
<b>Уеб сайт на проекта:</b> <a href='http://teamviewer.com/'>http://teamviewer.com</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage teamviewer
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage "http://download.teamviewer.com/download/teamviewer.i686.rpm"
    fi
  fi
}

install_tor() {
  if isInstalled torbrowser-launcher; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$torIcon" \
      --text="<b>Tor Browser Launcher</b>

Надеждно и лесно изтегляне, проверяване, инсталиране и стартиране на Tor браузъра в Linux .

<b>Лиценз:</b> MIT
<b>Уеб сайт на проекта:</b> <a href='https://github.com/micahflee/torbrowser-launcher'>https://github.com/micahflee/torbrowser-launcher</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage torbrowser-launcher
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage torbrowser-launcher
    fi
  fi
}

install_mscorefonts(){
  if isInstalled msttcorefonts; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$msIcon" \
      --text="<b>Msttcorefonts</b>

Инсталира Microsoft TrueType шрифтовете за по добра Windows съвместимост.

<b>Лиценз:</b> GPLv2
<b>Уеб сайт на проекта:</b> <a href='http://mscorefonts2.sourceforge.net/'>http://mscorefonts2.sourceforge.net</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage msttcorefonts
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage msttcorefonts
    fi
  fi
}

addSudo() {
  if grep --quiet -w "$user ALL=(ALL) ALL" /etc/sudoers; then
    BtStatus="Изтрий"
  else
    BtStatus="Добави"
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$sudoIcon" \
      --text="<b>Sudo</b>

Добавете или изтрийте потребителя <b>$user</b> от групата sudo

Командата sudo позволява на потребителя да изпълнява команди като root или друг потребител, придобивайки администраторски/root права над системата." \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" ==  Добави ]]; then
      echo "$user ALL=(ALL) ALL" >> /etc/sudoers
      notifyUser "Добавени са sudo права за потребителя <b>$user</b>"
      log "INFO:Добавени са sudo права за потребителя $user"
    elif [[ "$BtStatus" ==  Изтрий ]]; then
      sed -i '/'$user'/d' /etc/sudoers
      notifyUser "Премахнати са sudo правата за потребителя <b>$user</b>"
      log "INFO:Премахнати са sudo правата за потребителя $user"
    else
      exit 1
    fi
  fi
}

autoLogin(){
  rc="/etc/gdm/custom.conf"

  if grep --quiet -w "AutomaticLogin=$user" "$rc"; then
    BtStatus="Премахни"
  else
    BtStatus="Добави"
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$loginIcon" \
      --text="<b>AutoLogin</b>
Добавете или премахнете автоматичното влизане в системата за потребителя <b>$user</b> ." \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" ==  Добави ]]; then
      sed -i  '/^\[daemon\]$/a AutomaticLogin='$user'' "$rc"
      sed -i '/^\[daemon\]$/a AutomaticLoginEnable=True' "$rc"
      notifyUser "Добавено е автоматично влизане във системата за потребителя <b>$user</b>"
      log "INFO:Добавено е автоматично влизане във системата за потребителя $user"
    elif [[ "$BtStatus" ==  Премахни ]]; then
      sed -i '/'AutomaticLoginEnable'/d' "$rc"
      sed -i '/'$user'/d' "$rc"
      notifyUser "Премахнато е автоматичното влизане за потребителя <b>$user</b>"
      log "INFO:Премахнато е автоматичното влизане за потребителя $user"
   fi
  fi
}

setSelinux() {
  if grep --quiet ^SELINUX=permissive$ /etc/selinux/config; then
    BtStatus="Включи"
  else
    BtStatus='Изключи'
  fi

  yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$selinuxIcon" \
      --text="<b>SELinux</b>

Изключване или Включване на SELinux защитната среда." \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" ==  Включи ]]; then
      setenforce 1 > /dev/null
      sed -i 's/^SELINUX=.*$/SELINUX=enforcing/g' /etc/selinux/config
      notifyUser "Включване на SELinux!"
      log "INFO:Включване на SELinux!"
    elif [[ "$BtStatus" == Изключи ]]; then
      setenforce 0 > /dev/null
      sed -i 's/^SELINUX=.*$/SELINUX=permissive/g' /etc/selinux/config
      notifyUser "Изключване на SELinux!"
      log "INFO:Изключване на SELinux!"
    fi
  fi
}

install_playonlinux(){
  if isInstalled playonlinux; then
    BtStatus="Премахни"
  else
    BtStatus='Инсталирай'
  fi

 yad --title="$prog" --width=420 \
      --window-icon="$window_icon" \
      --image="$playonlinuxIcon" \
      --text="<b>PlayOnLinux</b>

Графичен софтуер който е съвместим в Wine, което позволява лесно и удобно на потребителите да инсталират Windows Linux-базирани видео игри, Microsoft Office и др.

<b>Лиценз:</b> GPL/LGPL
<b>Уеб сайт на проекта:</b> <a href='https://www.playonlinux.com/en/'>https://www.playonlinux.com/en</a>" \
      --selectable-labels \
      --button="$BtStatus":0 \
      --center
  ret=$?

  if [[ "$ret" -eq "0" ]]; then
    if [[ "$BtStatus" == Премахни ]]; then
      removePackage playonlinux
    elif [[ "$BtStatus" == Инсталирай ]]; then
      installPackage nc playonlinux
    fi
  fi
}

install_intel_driver(){
  if isInstalled libva-intel-driver libva-utils libva; then
    notifyUser "Вече е инсталиран драйвер"
    log "INFO:Вече е инсталиран драйвер"
  else
    installPackage libva-intel-driver libva-utils
  fi
}

install_nvidia_driver(){
  if isInstalled nvidia-x11-drv nvidia-detect "$(nvidia-detect)" libva-vdpau-driver libva-utils libva; then
    notifyUser "Вече е инсталиран драйвер"
    log "INFO:Вече е инсталиран драйвер"
  else
    installPackage nvidia-detect
    installPackage nvidia-x11-drv "$(nvidia-detect)" nvidia-x11-drv-32bit libva-vdpau-driver libva-utils libva
  fi
}

install_amd_driver(){
  value=${vga#*HD}
  Rx_xxx='R[0-9] [0-9]{3}' # for R series
  if [[ $vga =~ $Rx_xxx ]] || [[ $value -ge 5000 ]]; then
    if isInstalled fglrx-x11-drv kmod-fglrx fglrx-x11-drv-32bit liba-utils libva; then
      notifyUser "Вече е инсталиран драйвер"
      log "INFO:Вече е инсталиран драйвер"
    else
      installPackage fglrx-x11-drv kmod-fglrx fglrx-x11-drv-32bit libva-utils libva
    fi
  else
    if isInstalled fglrx-x11-drv kmod-fglrx-legacy fglrx-legacy-x11-drv-32bit liba-utils libva; then
      notifyUser "Вече е инсталиран драйвер"
      log "INFO:Вече е инсталиран драйвер"
    else
      installPackage fglrx-x11-drv kmod-fglrx-legacy fglrx-legacy-x11-drv-32bit libva-utils libva
    fi
  fi
}

install_bumblebee(){
  if isInstalled bumblebee; then
    notifyUser "Вече е инсталиран"
    log "INFO:Вече е инсталиран драйвер"
  else
    # http://elrepo.org/tiki/bumblebee
    removePackage xorg-x11-glamor
    installPackage bumblebee kmod-bbswitch kmod-nvidia VirtualGL libbsd nvidia-x11-drv-32bit.x86_64 libva-vdpau-driver libva-utils libva
    usermod -G bumblebee "$user"
    cat << EOF > /etc/bumblebee/bumblebee.conf
[bumblebeed]
VirtualDisplay=:8
KeepUnusedXServer=false
ServerGroup=bumblebee
TurnCardOffAtExit=false
NoEcoModeOverride=false
Driver=nvidia
XorgConfDir=/etc/bumblebee/xorg.conf.d

[optirun]
Bridge=auto
VGLTransport=proxy
PrimusLibraryPath=/usr/lib/primus:/usr/lib32/primus
AllowFallbackToIGC=false

[driver-nvidia]
KernelDriver=nvidia
PMMethod=bbswitch
LibraryPath=/usr/lib64/nvidia:/usr/lib64/vdpau:/usr/lib/nvidia:/usr/lib/vdpau
XorgModulePath=/usr/lib64/xorg/modules/extensions/nvidia,/usr/lib64/xorg/modules/drivers,/usr/lib64/xorg/modules

XorgConfFile=/etc/bumblebee/xorg.conf.nvidia

[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau
EOF
    sed -i 's/Exec=.*/Exec=optirun nvidia-settings -c :8.0/' /usr/share/applications/nvidia-settings.desktop
  fi
}

info_driver(){
  yad --title="Информация за драйвер" --selectable-labels --text-align=left --text="INTEL: използва се само вградената в процесора видео карта\n\nNVIDIA: използва се само дискретната видео карта\n\nBUMBLEBEE: дава възможност за динамично използване на двете видео карти\n\n" \
      --window-icon="$window_icon" \
      --width="200" --height="300" \
      --button="ОК":0 \
      --image="$window_icon" \
      --center
}

install_video(){
  shopt -s nocasematch
  vga=$(lspci | grep -i "vga\|3d");
  amd='\bAMD\b'
  ati='\bATI\b'
  intel='\bINTEL\b'
  nvidia='\bNVIDIA\b'
  if [[ $vga =~ $intel ]] && [[ $vga =~ $nvidia ]]; then
    while :
    do
      choise=$(yad  --title="Хибриден драйвер" --name="INTEL/NVIDIA" \
                    --image="$image_icon" --image-on-top --window-icon="$window_icon" \
                    --width="450" --height="560" --center --fixed \
                    --print-column=2 --list --radiolist --column "Избери" --column null --column "Опция" --hide-column 2 \
                    --button="ОК":0 --button="Научи повече":2 --button="Затваряне":1 \
                    false 0 "INTEL" \
                    false 1 "NVIDIA" \
                    false 2 "BUMBLEBEE");
      ret=$?

      if [[ "$ret" -eq "2" ]]; then
        info_driver
      fi

      case ${choise} in
        "0|")install_intel_driver ;;
        "1|")install_nvidia_driver ;;
        "2|")install_bumblebee ;;
        *) break ;;
      esac
    done

    elif [[ $vga =~ $nvidia ]]; then
      install_nvidia_driver
    elif [[ $vga =~ $amd ]] || [[ $vga =~ $ati ]]; then
      install_amd_driver
    elif [[ $vga =~ $intel ]]; then
      install_intel_driver
    else
      notifyUser "Непозната видео карта, моля поискайте помощ в нашият форум!"
      log "ERROR:Непозната видео карта, моля поискайте помощ в нашият форум!"
    fi
    shopt nocasematch # restore case matching
}

ASKinstallVideo(){
  aks=$(yad --title="$prog" --width=420 --window-icon="$window_icon" --image=dialog-question --text='Искате ли да инсталирате видео драйверите?
<b>Моля, имайте предвид тази функция е все още експериментална!</b>' --button="Не":0 --button="Да":1 --center)
  ret=$?

  if [[ "$ret" -eq "1" ]]; then
    install_video
  else
    exit 1
  fi
}

# Show about dialog
info() {
  yad --title="$prog" --selectable-labels --text-align=left --text="<span font_weight='bold' font='17'>$prog $ver </span>\n\n\Програма, която ви позволява да инсталирате допълнителен софтуер като Skype, Chrome, Steam и др., също така, дава възможност да настройте допълнително вашата StotinkaOS, само с няколко щраквания на мишката.   \n\n<span font='9'>Copyright © 2015-2016 StotinkaOS Team\nwebsite: <a href='http://stotinkaos.net'>http://stotinkaos.net</a></span>" \
      --window-icon="$window_icon" \
      --width="600" --height="300" \
      --button="ОК":0 --button="Лиценз":2 --button="Затваряне":1 \
      --image="$window_icon" \
      --center
  ret=$?

  if [[ "$ret" -eq "2" ]]; then
    yad --title="$prog" --text-info --filename="$license" \
        --window-icon="$window_icon" \
        --width="500" --height="300" \
        --button="Затваряне":1 \
        --center
  fi
  menu
}

# Main menu
menu(){
while :
do
  choise=$(yad --title="$prog" --name="$prog" \
               --image="$image_icon" --image-on-top --window-icon="$window_icon" \
               --width="450" --height="630" --center --fixed \
               --print-column=2 --list --radiolist --column "Избери" --column null --column "Опция" --hide-column 2 \
               --button="ОК":0 --button="gtk-about":2 --button="Затваряне":1 \
               true 0 "Steam" \
               false 1 "Dropbox" \
               false 2 "Sudo" \
               false 3 "Google Chrome" \
               false 4 "Google Talk Plugin" \
               false 5 "Spotify Client" \
               false 6 "Sublime Text 3" \
               false 7 "Atom Text Editor" \
               false 8 "Skype" \
               false 9 "Viber" \
               false 10 "TeamViewer" \
               false 11 "Tor Browser Launcher" \
               false 12 "Msttcorefonts (Microsoft шрифтове)" \
               false 13 "VirtualBox-5.0" \
               false 14 "PlayOnLinux" \
               false 15 "Намиране и инсталиране на видео драйвер" \
               false 16 "SELinux" \
               false 17 "Автоматично влизане в системата");
  ret=$?

  if [[ "$ret" -eq "2" ]]; then
    info
  fi

  case ${choise} in
    "0|")install_steam ;;
    "1|")install_dropbox ;;
    "2|")addSudo ;;
    "3|")install_chrome ;;
    "4|")install_gtalk ;;
    "5|")install_spotify ;;
    "6|")install_sublimetext ;;
    "7|")install_atom ;;
    "8|")install_skype ;;
    "9|")install_viber ;;
    "10|")install_teamviewer ;;
    "11|")install_tor ;;
    "12|")install_mscorefonts ;;
    "13|")install_virtualbox ;;
    "14|")install_playonlinux ;;
    "15|")ASKinstallVideo ;;
    "16|")setSelinux ;;
    "17|")autoLogin ;;
    *) break ;;
  esac
done
}

menu

# Please report bugs at <https://github.com/StotinkaOS/sos-easy-install/issues>
####### End of the Script ## ###################
